title: Gourmet Explorer
description: Discovering culinary delights around the world
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # replace with your GitHub username

markdown: kramdown
permalink: /:year/:month/:day/:title/

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  cuisines:
    output: true
  cities:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true